# Generated by Django 3.1.2 on 2020-11-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_image_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image_field',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='addres',
            new_name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
